# Generated by Django 6.0.5 on 2026-06-03 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.CharField(max_length=80)),
                ('unidad', models.CharField(choices=[('m', 'Metros'), ('und', 'Unidades'), ('rollo', 'Rollos')], default='und', max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('proveedor', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='pedidos.pedido')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='pedidos.insumo')),
            ],
        ),
    ]
